spring:
  data:
    redis:
      host: redis-19970.c256.us-east-1-2.ec2.redns.redis-cloud.com
      username: default
      password: mwGJIRMJNPXi9775rlTOjF0hIqQGL4jX
      port: 19970
      ssl:
        enabled: true
  security:
    oauth2:
      client:
        registration:
          grepp:
            provider: grepp-auth
            client-id: grepp
            client-secret: secret
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            scope: openid, profile
            redirect-uri: http://localhost:8080/login/oauth2/code/grepp
        provider:
          grepp-auth:
            issuer-uri: http://localhost:8081
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: auth_service
              uri: https://localhost:8081
              predicates:
                - Path=/auth/**
            - id: user_service
              uri: https://localhost:8082
              predicates:
                - Path=/api/member/**
              filters:
                - AddRequestHeader=X-member-id, test
                - AddRequestHeader=X-member-role, ROLE_ADMIN

logging:
  level:
    root: info
    springframework:
      cloud:
        openfeign: trace
      client:
        RestTemplate: debug
      security: trace

jwt:
  secrete: sskfjsasdkfsdklfjwioesdfjslkdfjsdlkfjsdlf
  access-expiration: 3000
  refresh-expiration: 604800000